services:
  bootcamp:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - HASH=dockerized-version
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/ping"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 40s
      start_interval: 5s