build:
	@echo "Building Image"
	@docker compose build

tests:
	@echo "Running Tests for the application. This is done outside of docker"
	@mvn test

run:
	@echo "Running Application"
	@docker compose up